### ISSUE TITLE
Not retrieving any data from api

### ISSUE THREAD

**Issue by ronanhansel** [gumbarros/kepler#12]
![Screenshot_20200906-223202.jpg](https://user-images.githubusercontent.com/64572619/92329294-cdfba780-f090-11ea-90f3-5b5047cfbbe7.jpg)

**Comment by gumbarros** [comment]
Weird, here works normally

**Comment by gumbarros** [comment]
I managed to reproduce the error, the API returns data but json decodes that it is having problems

**Comment by ronanhansel** [comment]
Fixed
