### ISSUE TITLE
Graphics View return null widget

### ISSUE THREAD

**Issue by ronanhansel** [gumbarros/kepler#2]
@gumbarros can you check this and build a dummy layout?

**Comment by gumbarros** [comment]
Yes, i removed both these two widgets and the view renderized, i don't understand how to use flutter animations
![image](https://user-images.githubusercontent.com/52143624/92309222-ffce1a80-ef79-11ea-9935-96dcd41b12dc.png)

**Comment by ronanhansel** [comment]
Oh so that's why. I haven't declared the animation
